name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    env:
      EW_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: '20'
    - run: npm ci
    - uses: emulator-wtf/setup-ew-cli@v0
    - run: curl -o minimal.apk -sS https://maven.emulator.wtf/releases/wtf/emulator/minimal/0.0.2/minimal-0.0.2.apk 
    - run: curl -o minimal-test.apk -sS https://maven.emulator.wtf/releases/wtf/emulator/minimal/0.0.2/minimal-0.0.2-test.apk 
    - uses: ./
      with: 
        app: minimal.apk
        test: minimal-test.apk
