name: Test
permissions:
  contents: read
  id-token: write
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - uses: jdx/mise-action@v4.0.1 # zizmor: ignore[unpinned-uses] immutable tag
    - run: mise lint
    - uses: emulator-wtf/actions/setup-ew-cli@v1.0.1 # zizmor: ignore[unpinned-uses] immutable tag
    - uses: emulator-wtf/actions/configure-credentials@v1.0.1 # zizmor: ignore[unpinned-uses] immutable tag
      with:
        oidc-configuration-id: ${{ vars.EW_OIDC_ID }}
    - run: curl -o minimal.apk -sS https://maven.emulator.wtf/releases/wtf/emulator/minimal/0.0.2/minimal-0.0.2.apk
    - run: curl -o minimal-test.apk -sS https://maven.emulator.wtf/releases/wtf/emulator/minimal/0.0.2/minimal-0.0.2-test.apk
    - uses: ./
      with:
        app: minimal.apk
        test: minimal-test.apk
